Rectangle page implementation
ashotvdovychenko/web-lab-js pull request #6
Opened 2023-10-09 09:11 UTC by Pagendera

2023-10-10 14:14 UTC, ashotvdovychenko approved these changes

2023-10-10 21:23 UTC, neodavis requested changes

2023-10-10 21:23 UTC, neodavis commented on rectangle-page/rectangle-page.js
> +function calculateRectangle() {
No validation on input, user should see some error text

2023-10-10 21:23 UTC, neodavis commented on rectangle-page/rectangle-page.html
> +        <input type="number" id="length" oninput="calculateRectangle()">
Avoid oninput, migrate call of method in addEventListener in JS file

2023-10-10 21:23 UTC, neodavis commented on rectangle-page/rectangle-page.html
> +        <input type="number" id="width" oninput="calculateRectangle()">
add some styles for input (for page in general, avoid plain styled elements)

2023-10-10 21:23 UTC, neodavis commented on rectangle-page/rectangle-page.html
> +<body class="bg-primary container text-white">
as for me, would be better to migrate main content into something like card.

2023-10-12 21:58 UTC, neodavis approved these changes

2023-10-12 21:59 UTC, merged