birth-week-day-page implementation
ashotvdovychenko/web-lab-js pull request #7
Opened 2023-10-09 13:34 UTC by Pagendera

2023-10-10 14:28 UTC, ashotvdovychenko requested changes

2023-10-10 14:28 UTC, ashotvdovychenko commented on birth-week-day-page/birth-week-day-page.js
> +    const a = 14 - Math.floor(birthdate.getUTCMonth() / 12);
Algorithm requires  `(14 - month) / 12`
But in your case it is `14 - (month / 12)`

2023-10-10 14:28 UTC, ashotvdovychenko commented on birth-week-day-page/birth-week-day-page.js
> +    const m = birthdate.getUTCFullYear() - a;
m is equal to y.
m should be calculated in this way `month + 12 * a - 2`

2023-10-10 14:28 UTC, ashotvdovychenko commented on birth-week-day-page/birth-week-day-page.js
> +    const dayOfWeek = (birthdate.getUTCDay() + y + Math.floor(y / 4) - Math.floor(y / 100) + Math.floor(y / 400) + Math.floor((31 * m) / 12)) % 7;
`birthdate.getUTCDay()` already returns value from 0 to 6 (day of week).
Maybe use `getDate()` to get day of month?

2023-10-10 14:33 UTC, ashotvdovychenko commented on birth-week-day-page/birth-week-day-page.js
> +
And think about is it ok to user UTC methods?
It can make different results after transforming to UTC/

2023-10-10 21:11 UTC, neodavis requested changes

2023-10-10 21:11 UTC, neodavis commented on birth-week-day-page/birth-week-day-page.html
> +    <input type="date" id="birthdate" min="1583-01-01" oninput="calculateDay()" required>
Better use addEventListener in Js, instead of oninput usage in HTML

Template should avoid any specific logic (call of JS function is actually logic, that better be stored in one place - JS file)

2023-10-10 21:11 UTC, neodavis commented on birth-week-day-page/birth-week-day-page.html
> +    <input type="date" id="birthdate" min="1583-01-01" oninput="calculateDay()" required>
Is there any purpose of use "min" and "required" attributes?

Check pls, can we get rid of them?)

2023-10-10 21:11 UTC, neodavis commented on birth-week-day-page/birth-week-day-page.html
> +<body class="bg-primary container text-white">
Check, is there any possibility to impove UI of design? Maybe use some cardlike version?

2023-10-10 21:11 UTC, neodavis commented on birth-week-day-page/birth-week-day-page.js
> +function calculateDay() {
Whole function looks so complicated, I see much easier way to solve it.

Need just to display daysOfWeek[birthdate.getDay()] for user and rearrange day names in array, any algorithm for this case is unnecessary)

2023-10-10 21:11 UTC, neodavis commented on birth-week-day-page/birth-week-day-page.html
> +
Too much empty lines at the end of the file, clean up code before commit)

2023-10-10 21:27 UTC, neodavis requested changes

2023-10-10 21:27 UTC, neodavis commented on birth-week-day-page/birth-week-day-page.html
> +    <input type="date" id="birthdate" min="1583-01-01" oninput="calculateDay()" required>
just noticed, that we should limit max user date choose with today date

2023-10-10 21:37 UTC, neodavis commented on birth-week-day-page/birth-week-day-page.js
> +    document.getElementById("result").textContent = daysOfWeek[dayOfWeek];
function that named calculateDay() should not have any display logic, otherwise it is GOD function

2023-10-11 14:36 UTC, Pagendera commented on birth-week-day-page/birth-week-day-page.html
> +    <input type="date" id="birthdate" min="1583-01-01" oninput="calculateDay()" required>
This algorithm works only after 1583, as the Gregorian calendar began to operate then, so min is required

2023-10-11 14:39 UTC, Pagendera commented on birth-week-day-page/birth-week-day-page.js
> +function calculateDay() {
This algorithm is necessary, please, check the task conditions

2023-10-12 23:18 UTC, neodavis approved these changes

2023-10-12 23:18 UTC, ashotvdovychenko approved these changes

2023-10-12 23:20 UTC, ashotvdovychenko requested changes

2023-10-12 23:20 UTC, ashotvdovychenko commented on birth-week-day-page/birth-week-day-page.html
> +            <label for="birthdate">Length:</label>
Why length?

2023-10-12 23:24 UTC, ashotvdovychenko approved these changes

2023-10-12 23:25 UTC, merged